resources:
  - namespace.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: rancher
    repo: https://releases.rancher.com/server-charts/latest
    version: 2.11.2
    releaseName: rancher
    namespace: rancher
    valuesFile: values.yaml
    kubeVersion: 1.32.0