apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -dc11a

resources:
- ../../../../base/coredns

patches:
- path: remove-clusterip-patch.yaml
  target:
    kind: Service
    name: kube-dns
