apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Name suffix for all resources
nameSuffix: -dc11a

# Include the base Longhorn manifests
resources:
  - ../../../../base/longhorn

# Common labels to apply to all resources
commonLabels:
  app.kubernetes.io/instance: longhorn-dc11a
  app.kubernetes.io/part-of: longhorn
  app.kubernetes.io/managed-by: kustomize

# Namespace to deploy all resources
namespace: longhorn-system
